[package]
name = "sdf3d"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
klystron = { path = "../klystron" }
anyhow = "1"
notify = "4.0"
structopt = { version = "0.3", default-features = false }
shaderc = "0.7"
